# Generated by Django 4.2.16 on 2026-09-16 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='System-generated pseudonymous identifier. Never maps to real patient name.', unique=True)),
                ('dob_year', models.PositiveSmallIntegerField(help_text='Birth year only. No full date of birth stored.')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Unknown')], help_text='Biological sex — required for sex-specific QTc thresholds (Rautaharju 1992).', max_length=1)),
                ('facility_id', models.CharField(help_text='Anonymised facility code. Not a real facility name.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient (pseudonymized)',
                'ordering': ['-created_at'],
            },
        ),
    ]
