# Generated by Django 4.2.16 on 2026-09-17 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='male', help_text='FHIR R4 compliant gender.', max_length=16),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_identifier',
            field=models.CharField(blank=True, default='', help_text='Official Patient Identifier / IPP.', max_length=64),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Birth year (derived from birth_date or specified directly).', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='facility_id',
            field=models.CharField(blank=True, default='DISP-CENTRE-01', help_text='Health facility / dispensary code.', max_length=64),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pseudo_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='System-generated unique identifier (used as FHIR resource id).', unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Unknown')], default='M', help_text='Biological sex — required for sex-specific QTc thresholds (Rautaharju 1992).', max_length=1),
        ),
    ]
