# Generated by Django 4.2.16 on 2026-09-16 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_text', models.TextField(help_text='Auto-generated clinical summary based on flags.')),
                ('physician_notes', models.TextField(blank=True, help_text='Manual notes added by the reviewing physician.')),
                ('severity', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Physician Review'), ('REVIEWED', 'Reviewed (Notes Added)'), ('SIGNED', 'Electronically Signed')], db_index=True, default='PENDING_REVIEW', max_length=15)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='ecg.processingresult')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
