# Generated by Django 4.2.16 on 2026-09-17 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the case was claimed.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='Physician who took ownership of this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='emergency_notes',
            field=models.TextField(blank=True, help_text='Immediate instructions transmitted to field team in case of vital emergency.'),
        ),
        migrations.AddField(
            model_name='report',
            name='retake_reason',
            field=models.TextField(blank=True, help_text='Technical reason for requesting ECG re-acquisition.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', "En attente d'attribution"), ('IN_REVIEW', "Pris en charge (en cours d'analyse)"), ('SIGNED', 'Validé et signé électroniquement'), ('RETAKE_REQUESTED', 'Réacquisition demandée'), ('EMERGENCY_TRANSFER', 'Urgence SAMU déclenchée')], db_index=True, default='PENDING_REVIEW', max_length=20),
        ),
    ]
