# Generated by Django 4.2.16 on 2026-09-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Raw ECG file. Stored encrypted at rest.', upload_to='ecg_uploads')),
                ('file_hash', models.CharField(help_text='SHA-256 of the uploaded file content.', max_length=64)),
                ('fmt', models.CharField(choices=[('wfdb', 'WFDB (.mat + .hea)'), ('csv', 'CSV'), ('edf', 'EDF/EDF+')], default='wfdb', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting processing'), ('PROCESSING', 'Pipeline running'), ('DONE', 'Processing complete'), ('ERROR', 'Processing failed')], db_index=True, default='PENDING', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('fs', models.IntegerField(blank=True, help_text='Sampling frequency in Hz', null=True)),
                ('lead_count', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecg_records', to='patients.patient')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervals_json', models.JSONField(help_text='Serialised IntervalResult from ecg.pipeline.intervals.')),
                ('flags_json', models.JSONField(help_text='List of Flag dicts from ecg.pipeline.rule_engine — each includes citation.')),
                ('severity', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('lead_used', models.CharField(default='II', max_length=10)),
                ('partial', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ecg.ecgrecord')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
