# Generated by Django 4.2.16 on 2026-09-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcgStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=64)),
                ('patient_name', models.CharField(max_length=128)),
                ('patient_birth', models.DateField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, max_length=1)),
                ('identity_verified', models.BooleanField(default=False)),
                ('identity_method', models.CharField(blank=True, max_length=32)),
                ('file', models.FileField(upload_to='ecg_uploads/%Y/%m/')),
                ('file_format', models.CharField(blank=True, max_length=8)),
                ('paced', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('acquired', 'Acquis'), ('analysed', 'Analyse automatique faite'), ('rejected', 'Rejete, reacquisition requise'), ('transmitted', 'Transmis au medecin'), ('reviewing', 'En cours de lecture'), ('signed', 'Compte rendu signe'), ('delivered', 'Restitue au SIH')], db_index=True, default='acquired', max_length=16)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('report_text', models.TextField(blank=True)),
                ('triage_level', models.CharField(blank=True, db_index=True, max_length=8)),
                ('triage_priority', models.IntegerField(blank=True, db_index=True, null=True)),
                ('escalated', models.BooleanField(db_index=True, default=False)),
                ('physician_report', models.TextField(blank=True)),
                ('signature', models.CharField(blank=True, max_length=256)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('transmitted_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecg_acquired', to=settings.AUTH_USER_MODEL)),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecg_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['triage_priority', '-acquired_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(max_length=40)),
                ('from_state', models.CharField(blank=True, max_length=16)),
                ('to_state', models.CharField(blank=True, max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ecg.ecgstudy')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
