# Generated by Antigravity - Data migration from ECGRecord to EcgStudy
from django.db import migrations


def migrate_records_forward(apps, schema_editor):
    ECGRecord = apps.get_model('ecg', 'ECGRecord')
    EcgStudy = apps.get_model('ecg', 'EcgStudy')
    AuditEvent = apps.get_model('ecg', 'AuditEvent')

    for record in ECGRecord.objects.select_related('patient').all():
        patient = record.patient
        patient_name = f"{patient.first_name} {patient.last_name}".strip() if patient else "Inconnu"
        patient_id = str(patient.pseudo_id) if patient else f"REC-{record.id}"
        patient_birth = patient.birth_date if patient else None
        patient_sex = (patient.sex or "")[:1] if patient else ""

        # Default state
        state = "analysed"
        signed_at = None
        physician_report = ""
        signature = ""

        # Check if there is an associated report
        try:
            res = getattr(record, 'result', None)
            if res and hasattr(res, 'report'):
                rep = res.report
                if rep.status == "SIGNED":
                    state = "signed"
                    signed_at = rep.signed_at
                    physician_report = rep.physician_notes or rep.draft_text
                    signature = rep.electronic_signature or "SIG_MIGRATED"
                elif rep.status == "IN_REVIEW":
                    state = "reviewing"
                else:
                    state = "transmitted"
        except Exception:
            pass

        study = EcgStudy.objects.create(
            patient_id=patient_id,
            patient_name=patient_name or "Inconnu",
            patient_birth=patient_birth,
            patient_sex=patient_sex,
            identity_verified=True,
            identity_method="Dossier National",
            file=record.file,
            file_format=record.fmt or "csv",
            paced=False,
            state=state,
            acquired_at=record.uploaded_at,
            analysed_at=record.uploaded_at,
            signed_at=signed_at,
            physician_report=physician_report,
            signature=signature,
            triage_level="ROUTINE",
            triage_priority=3,
        )

        AuditEvent.objects.create(
            study=study,
            action="migration_initiale",
            from_state="acquired",
            to_state=state,
            detail={"migrated_from_ecgrecord_id": record.id}
        )


def migrate_records_backward(apps, schema_editor):
    EcgStudy = apps.get_model('ecg', 'EcgStudy')
    EcgStudy.objects.filter(events__action="migration_initiale").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0002_ecgstudy_auditevent'),
    ]

    operations = [
        migrations.RunPython(migrate_records_forward, migrate_records_backward),
    ]
