# Generated by Django 4.2.16 on 2026-09-16 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(default='SYSTEM', help_text='Snapshot of username at event time (preserved even if user is deleted).', max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'Record created'), ('UPDATE', 'Record updated'), ('SIGN', 'Report signed by physician'), ('PROCESS_START', 'ECG processing started'), ('PROCESS_DONE', 'ECG processing completed'), ('PROCESS_ERROR', 'ECG processing failed'), ('EXPORT_FHIR', 'FHIR bundle exported'), ('LOGIN', 'User logged in'), ('LOGIN_FAILED', 'Login attempt failed'), ('LOGOUT', 'User logged out'), ('PASSWORD_CHANGED', 'Password changed'), ('INVITE', 'User account invited/created'), ('SUSPEND', 'User account suspended'), ('REINSTATE', 'User account reinstated'), ('ROLE_CHANGED', 'User role changed'), ('PERMISSION_DENY', 'Access denied (403)'), ('VIEW', 'Record viewed')], db_index=True, max_length=30)),
                ('target_type', models.CharField(db_index=True, help_text="Django model name, e.g. 'ECGRecord', 'Report'.", max_length=50)),
                ('target_id', models.CharField(db_index=True, help_text='PK or UUID of the affected record.', max_length=64)),
                ('old_value', models.JSONField(blank=True, help_text='JSON snapshot of the record state before the action.', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='JSON snapshot of the record state after the action.', null=True)),
                ('ip_hash', models.CharField(blank=True, help_text='SHA-256 of the request IP address (not stored in plaintext).', max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, help_text="Arbitrary context, e.g. {flag_codes: ['QTC_CRITICAL'], severity: 'CRITICAL'}.", null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action; null means SYSTEM (pipeline).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
